# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

PDE_Kernel <- function(DataVector, DomainX, PR, NSeq, NData) {
    .Call(`_PDEnaiveBayes_PDE_Kernel`, DataVector, DomainX, PR, NSeq, NData)
}

dist1d <- function(x) {
    .Call(`_PDEnaiveBayes_dist1d`, x)
}

quantile1_large_vec <- function(x, probs) {
    .Call(`_PDEnaiveBayes_quantile1_large_vec`, x, probs)
}

quantile4LargeVectors <- function(x, probs) {
    .Call(`_PDEnaiveBayes_quantile4LargeVectors`, x, probs)
}

